config/routes.rb
Gitscm::Application.routes.draw do

  constraints(:host => 'whygitisbetterthanx.com') do
    root :to => 'site#redirect_wgibtx', as: :whygitisbetterthanx
  end

  constraints(:host => 'progit.org') do
    root :to => 'site#redirect_book', as: :progit
    get '*path' => 'site#redirect_book'
  end

#  constraints(:subdomain => 'book') do
#    root :to => 'site#redirect_book'
#    get '*path' => 'site#redirect_combook'
#  end

  get "site/index"

  get "/doc" => "doc#index"
  get "/docs" => "doc#ref"
  get "/docs/howto/:file", to: redirect {|path_params, req|
    "https://github.com/git/git/blob/master/Documentation/howto/#{path_params[:file]}.txt"
  }
  get "/docs/:file.html" => "doc#man", :as => :doc_file_html, :file => /[\w\-\.]+/
  get "/docs/:file" => "doc#man", :as => :doc_file, :file => /[\w\-\.]+/
  get "/docs/:file/:version" => "doc#man", :version => /[^\/]+/
  get "/doc/ext" => "doc#ext"

  %w{man ref git}.each do |path|
    get "/#{path}/:file" => redirect("/docs/%{file}")
    get "/#{path}/:file/:version" => redirect("/docs/%{file}/%{version}"),
    :version => /[^\/]+/
  end

  resource :book do
    get "/ch:chapter-:section.html"    => "books#chapter"
    get "/:lang/ch:chapter-:section.html" => "books#chapter"
    get "/index"                          => redirect("/book")
    get "/commands"                       => "books#commands"
    get "/:lang/v:edition"                => "books#show"
    get "/:lang/v:edition/:slug"          => "books#section"
    get "/:lang/v:edition/:chapter/:link" => "books#link", chapter: /(ch|app)\d+/
    get "/:lang"                          => "books#show", as: :lang
    get "/:lang/:slug"                    => "books#section", as: :slug
  end
  post "/update"   => "books#update"

  get "/download"               => "downloads#index"
  get "/download/:platform"     => "downloads#download"
  get "/download/gui/:platform" => "downloads#gui"

  resources :downloads, :only => [:index] do
    collection do
      get "/guis"       => "downloads#guis"
      get "/installers" => "downloads#installers"
      get "/logos"       => "downloads#logos"
      get "/latest"     => "downloads#latest"
    end
  end

  get "/:year/:month/:day/:slug" => "blog#post",  :year   => /\d{4}/,
                                                    :month  => /\d{2}/,
                                                    :day    => /\d{2}/

  get "/blog/:year/:month/:day/:slug" => "blog#post",  :year   => /\d{4}/,
                                                    :month  => /\d{2}/,
                                                    :day    => /\d{2}/

  get "/blog.rss" => "blog#feed"
  get "/blog" => "blog#index"

  get "/publish"  => "doc#book_update"
  post "/related" => "doc#related_update"

  get "/about" => "about#index"
  get "/about/:section" => "about#index"

  get "/videos" => "doc#videos"
  get "/video/:id" => "doc#watch"

  get "/community" => "community#index"

  get "/search" => "site#search"
  get "/search/results" => "site#search_results"

  # mapping for jasons mocks
  get "/documentation" => "doc#index"
  get "/documentation/reference" => "doc#ref"
  get "/documentation/reference/:file.html" => "doc#man"
  get "/documentation/book" => "doc#book"
  get "/documentation/videos" => "doc#videos"
  get "/documentation/external-links" => "doc#ext"

  get "/course/svn" => "site#svn"
  get "/sfc" => "site#sfc"
  get "/trademark" => "site#trademark"

  get "/contributors" => redirect("https://github.com/git/git/graphs/contributors")

  root :to => 'site#index'
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
    expires_in 10.minutes, :public => true

    @section    = "home"
    @subsection = ""
  end

  def search
    @term = sname = params['search'].to_s.downcase
    @data = search_term(sname)
    render :partial => 'shared/search'
  end

  def search_results
    @term = sname = params['search'].to_s.downcase
    data = search_term(sname, true)
    @top = []
    @rest = []
    data[:results].each do |type|
      type[:matches].each do |hit|
        if hit[:score] >= 1.0
          @top << hit
        else
          @rest << hit
        end
      end
    end
    @top.sort! { |a, b| b[:score] <=> a[:score] }
    @rest.sort! { |a, b| b[:score] <=> a[:score] }
    render "results"
  end

  def search_term(sname, highlight = false)
    data = {
      :term => sname,
      :results => []
    }

    if results = Doc.search(sname)
      data[:results] << results
    end

    if results = Section.search(sname, :lang => 'en')
      data[:results] << results
    end

    data
  end

  def svn
  end

  def redirect_wgibtx
    redirect_to "https://git-scm.com/about"
  end

  def redirect_book
    current_uri = request.env['PATH_INFO']
    if current_uri == '/'
      redirect_to "https://git-scm.com/book"
    else
      redirect_to "https://git-scm.com#{current_uri}"
    end
  end

end

app/helpers/site_helper.rb
module SiteHelper
  def highlight_no_html(high)
    strip_tags(high.to_s)
      .gsub('[highlight]', '<span class="highlight">')
      .gsub('[xhighlight]', '</span>')
  end

  def rchart(title, data, extra = nil)
    git = data[0][1]
    svn = data[1][1]
    out  = "<tr>"
    out += "<td nowrap>#{title}</td>"
    out += "<td class='desc'>#{extra}</td>"
    out += "<td class='number'>#{sprintf("%5.2f", git)}</td>"
    out += "<td class='number'>#{sprintf("%5.2f", svn)}</td>"
    out += "<td class='number'>#{(svn / git).floor}x</td>"
    out += "</tr>"
  end

  def trchart(title, data, extra = nil)
    git = data[1][1]
    git2 = data[0][1]
    svn = data[2][1]
    out  = "<tr>"
    out += "<td nowrap>#{title}</td>"
    out += "<td class='desc'>#{extra}</td>"
    if git2
      out += "<td class='number'>#{sprintf("%5.1f", git2)}</td>"
    else
      out += "<td></td>"
    end
    out += "<td class='number'>#{sprintf("%5.1f", git)}</td>"
    out += "<td class='number'>#{sprintf("%5.1f", svn)}</td>"
    out += "</tr>"
  end


  def gchart(title, data)
    labels = data.map {|v| v[0] }
    vals = data.map {|v| v[1] }
    
    v = vals.join(',')
    l = labels.join('|')

    scale = vals.max
    c = "<img src=\"https://chart.googleapis.com/chart?"
    c += "chxt=x" + "&amp;"
    c += "cht=bvs" + "&amp;"
    c += "chl=#{l}" + "&amp;"
    c += "chd=t:#{v}" + "&amp;"
    c += "chds=0,#{scale}" + "&amp;"
    c += "chs=100x125" + "&amp;"
    if vals.size == 3
      c += "chco=E09FA0|E09FA0|E05F49" + "&amp;"
    else
      c += "chco=E09FA0|E05F49" + "&amp;"
    end
    c += "chf=bg,s,fcfcfa&"
    c += "chtt=#{title}"
    c += "\" alt=\"init benchmarks\" />"
    c
  end
end

app/views/site/index.html.erb
<div id="front-content">
  <section id="front-navigation">
    <nav id="front-nav">
      <ul>
        <li id="nav-about">
          <%= link_to about_path do %>
            <img src="/images/icons/nav-about@2x.png" width="74" height="74" />
            <h3>About</h3>
            <p>The advantages of Git compared to other source control systems.</p>
          <% end %>
        </li>
        <li id="nav-documentation">
          <%= link_to doc_path do %>
            <img src="/images/icons/nav-documentation@2x.png" width="74" height="74" />
            <h3>Documentation</h3>
            <p>Command reference pages, Pro Git book content, videos and other material.</p>
          <% end %>
        </li>
        <li id="nav-downloads">
          <%= link_to downloads_path do %>
            <img src="/images/icons/nav-downloads@2x.png" width="74" height="74" />
            <h3>Downloads</h3>
            <p>GUI clients and binary releases for all major platforms.</p>
          <% end %>
        </li>
        <li id="nav-community">
          <%= link_to community_path do %>
            <img src="/images/icons/nav-community@2x.png" width="74" height="74" />
            <h3>Community</h3>
            <p>Get involved! Bug reporting, mailing list, chat, development and more.</p>
          <% end %>
        </li>
      </ul>
    </nav>
    <div id="front-book">
      <img src="/images/progit2.png" width="56" height="74" />
      <p>
        <strong><a href="/book">Pro Git</a></strong>
        by Scott Chacon and Ben Straub is available to
        <a href="/book">read online for free</a>.
        Dead tree versions are available on <a href="http://www.amazon.com/Pro-Git-Scott-Chacon/dp/1484200772?ie=UTF8&camp=1789&creative=9325&creativeASIN=1430218339&linkCode=as2&tag=git-sfconservancy-20">Amazon.com</a>.
      </p>
    </div>
  </section>
  <section id="front-downloads">
    <%= partial 'shared/monitor' %>
    <table>
      <tr>
        <td nowrap="true"><%= link_to "Graphical UIs", "/downloads/guis", class: 'icon gui', id: 'gui-link' %></td>
        <td nowrap="true"><%= link_to "Tarballs", "https://www.kernel.org/pub/software/scm/git/", class: 'icon older-releases' %></td>
      </tr>
      <tr>
        <td nowrap="true"><%= link_to "Windows Build", "/download/win", class: 'icon windows', id: 'alt-link' %></td>
        <td nowrap="true"><%= link_to "Source Code", "https://github.com/git/git", class: 'icon source' %></td>
      </tr>
    </table>
</section>
</div>

<section id="companies-projects">
  <h3> Companies &amp; Projects Using Git </h3>
  <ul>
    <li><%= link_to "Google", "https://github.com/google", class: 'google' %></li>
    <li><%= link_to "Facebook", "https://github.com/facebook", class: 'facebook' %></li>
    <li><%= link_to "Microsoft", "https://github.com/Microsoft", class: 'microsoft' %></li>
    <li><%= link_to "Twitter", "https://github.com/twitter", class: 'twitter' %></li>
    <li><%= link_to "LinkedIn", "https://github.com/linkedin", class: 'linked-in' %></li>
    <li><%= link_to "Netflix", "https://github.com/netflix", class: 'netflix' %></li>
    <li><%= link_to "Perl", "https://perl5.git.perl.org/perl.git", class: 'perl' %></li>
    <li><%= link_to "PostgreSQL", "https://git.postgresql.org/gitweb/", class: 'postgresql' %></li>

    <li><%= link_to "Android", "https://android-review.googlesource.com/#/q/status:open,n,z", class: 'android' %></li>
    <li><%= link_to "Linux", "https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git", class: 'linux' %></li>
    <li><%= link_to "Ruby on Rails", "https://github.com/rails/rails", class: 'rails' %></li>
    <li><%= link_to "Qt", "https://code.qt.io/cgit/", class: 'qt' %></li>
    <li><%= link_to "Gnome", "https://git.gnome.org/browse/", class: 'gnome' %></li>
    <li><%= link_to "Eclipse", "https://git.eclipse.org/c/", class: 'eclipse' %></li>
    <li><%= link_to "KDE", "https://quickgit.kde.org/", class: 'kde' %></li>
    <li><%= link_to "X", "https://cgit.freedesktop.org/xorg/xserver/", class: 'x' %></li>
</ul>
</section>

app/views/site/results.html.erb
<% @section = "search" %>
<% @subsection = "" %>
<% @page_title = "Search results for #{h(@term)}" %>

<% content_for :sidebar do %>
  <%= render 'shared/related' %>
<% end %>

<div id="main">
  
  <h1><%= raw "Search results for <strong>#{h(@term)}</strong>" %></h1>
  
  <% if @top.size > 0 %>
    <div class="callout top-matches">
      <ol class="full-search-results">
        <% @top.each do |hit| %> 
          <li>
            <h3><%= link_to hit[:name], hit[:url] %></h3>
            <%= link_to hit[:url], hit[:url], class: 'url' %>
            <p><%= raw highlight_no_html(hit[:highlight]) %></p>
          </li>
        <% end %>
      </ol>
    </div>
  <% end # @top.size > 0 %>

  <% if @rest.size > 0 %>
    <ol class="full-search-results">
      <% @rest.each do |hit| %>
        <li>
          <span class="relevancy">
            <% total = (hit[:score] * 10).ceil %>
            <% rest  = 10 - total %>
            <% rest.times do %>
              <img src="/images/icons/grey-dot.png" alt="">
            <% end %>
            <% total.times do %>
              <img src="/images/icons/green-dot.png" alt="">
            <% end %>
          </span>
          <h3>
            <%= link_to hit[:name], hit[:url] %>
          </h3>
          <%= link_to hit[:url], hit[:url], class: 'url' %>
          <p>
            <%= raw highlight_no_html(hit[:highlight]) %>
          </p>
        </li>
      <% end %>
    </ol>
  <% end %>
  
  <% if @rest.size + @top.size == 0 %>
    <h2> Sorry, no search matches </h2>
  <% end %>
</div>

app/views/site/sfc.html.erb
<div id="main">
  <h1 id="sfc">Git and Software Freedom Conservancy</h1>

  <p>Git is a member project of <a href="https://sfconservancy.org/">Software
  Freedom Conservancy</a>.  Conservancy is a not-for-profit organization that
  provides financial and administrative assistance to open source projects.

  <h2 class="section-start">Donation</h2>

  <p>Conservancy accepts donations on git's behalf. In the past, project money has
  typically gone to defraying travel costs for developers to come to our annual
  <a href="https://git.wiki.kernel.org/index.php/GitTogether">GitTogether</a>
  mini-conference.  A portion of the money goes to Conservancy to cover their
  operating expenses. You can also donate <a
  href="https://sfconservancy.org/donate">directly</a> to Software
  Freedom Conservancy's general fund.

  <h3 class="title">Paypal</h3>
  <p>To donate to Git via PayPal:
  <div class="center">
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
      <input type="hidden" name="cmd" value="_s-xclick">
      <input type="hidden" name="hosted_button_id" value="GXTE9AECX4LAL">
      <input type="image"
             src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif"
             border="0" name="submit"
             alt="PayPal - The safer, easier way to pay online!">
      <img alt="" border="0" height="1" width="1"
           src="https://www.paypal.com/en_US/i/scr/pixel.gif">
    </form>
  </div>

  <h3 class="title">Check</h3>
  <p>We can also accept donations drawn in USD from banks in the USA
  (donations from banks outside of the US or not in USD should be handled
  by wire). Make checks payable to "Software Freedom Conservancy, Inc."
  and place "Directed donation: Git" in the memo field. Checks should be
  mailed to:
  <div class="center">
  <pre>
  Software Freedom Conservancy, Inc.
  137 Montague ST STE 380
  BROOKLYN, NY 11201 USA
  </pre>
  </div>

  <h3 class="title">Wire</h3>
  <p>Conservancy can accept wire donations, but the instructions vary
  depending on the country of origin. Please contact <a
    href="mailto:accounting@sfconservancy.org">accounting@sfconservancy.org</a>
  for instructions.

  <h3 class="title">Stock</h3>
  <p>Conservancy also accepts stock donations on behalf of the Git
  project. If you would like to donate stock, please contact <a
    href="mailto:accounting@sfconservancy.org">accounting@sfconservancy.org</a>
  for instructions on how to initiate the transfer.

</div>

app/views/site/trademark.html.erb
<div id="main">

<h1>GIT TRADEMARK POLICY</h1>

<h2>1 Purpose</h2>

<p>The Git Project is a member project of Software Freedom
Conservancy ("Conservancy"). Conservancy holds rights in the Marks
on behalf of the Git Project in accordance with its non-
profit charitable mission.</p>

<p>Conservancy has adopted this Policy to protect the Marks (as
defined below) and to make sure that the identity of Git software
and its free and open source nature is clear to everyone. By
using this Policy, the Git Project can spread the use of the
Git software while making sure that the Marks are protected in a
way that's consistent with U.S. trademark law.  This Policy is
written to allow all clear and appropriate use of the Marks while
disapproving use of the Marks in ways that could confuse users as
to where the software came from, or that implies an otherwise non-
existent association with the Git Project. By adhering to this
Policy, you help to promote to the public the freedom to use and
develop the Git software.</p>

<p>Throughout this Policy, the word "Marks" refers to the following:</p>

<ul>
<li><p>the literal mark "Git"</p></li>
<li><p>The logos and graphic marks displayed and available for
download at <a href="https://git-scm.com/downloads/logos">https://git-scm.com/downloads/logos</a></p></li>
<li><p>The slogan "the stupid content tracker"</p></li>
</ul>

<p>This Policy is only concerned with the Marks associated with the Git
Project, and does not address any copyrights associated with the
Git software.</p>

<h2>2 Guidelines for using the Marks</h2>

<h3>2.1 Trademark symbol on first mention</h3>

<p>The first prominent mention of a Mark should be immediately
followed by a symbol for, as applicable, a registered trademark
(®) or an unregistered trademark (™). For example: "Git™".</p>

<p>This requirement is waived in all contexts where such marks are
not required to protect the intellectual property rights associated
with the Marks, such as email, online discussion, and academic papers.
We encourage the use of the applicable symbols whenever possible, but
recognize that many users will omit them in non-commercial and informal
contexts.</p>

<p>You can use "Git and the Git logo are either registered trademarks
or trademarks of Software Freedom Conservancy, Inc., corporate home of
the Git Project, in the United States and/or other countries." when
you need to mention "Git" in e.g. list of trademarks held by other
people.</p>

<h3>2.2 Use of the Marks without written permission</h3>

<p>You may use the Marks without prior written permission (subject
to the other sections):</p>

<ol>
<li><p>To refer to the Git software in substantially unmodified
form. "Substantially unmodified" means built from the source
code provided by the Git Project, possibly with minor
modifications including but not limited to: the enabling or
disabling of certain features by default, translations into
other languages, changes required for compatibility with a
particular operating system distribution, or the inclusion of
bug-fix patches.</p></li>
<li><p>To identify the Git software as a distinct component of a
software offering.</p></li>
<li><p>To factually refer to the Git Project itself, its products,
or its protocols.</p></li>
</ol>

<p>In addition, you may use the Marks to refer to products,
services, or communities outside of the Git software and Git
Project without written permission in the following contexts:</p>

<ol start="4">
<li>When referring to Git software that is not substantially
unmodified, to say that such software is a "derivative of"
or "based on" Git.</li>
<li>When referring to a third-party software product and/or service that
is interoperable with the Git software, in the format "[Product Name]
for Git" -- provided that such use otherwise complies with the rest of
this Policy.
</ol>

<p>We do not charge a fee for a license to use the Marks
in these contexts. However, we do of course welcome donations.
If you're interested in donating to the Git Project, care of
Conservancy, visit <a href="https://git-scm.com/sfc">https://git-scm.com/sfc</a>.
Conservancy is a United States 501(c)(3) public charity.</p>

<h3>2.3 Prohibited usages of the Marks</h3>

<p>You may not use the Marks in the following ways:</p>

<ul>
<li><p>In any way likely to cause confusion as to the identity of the
Git Project, the provenance of its software, or the
software's license.</p></li>
<li><p>In any way that indicates a greater degree of association
between you and the Git Project than actually exists.</p></li>
<li><p>In any way that implies a designated successor to Git (e.g.,
"Git++" is not permitted).</p></li>
<li><p>In any way that indicates that Git favors one distribution,
platform, product, etc. over another except where explicitly
indicated in writing by Conservancy.</p></li>
<li><p>In any other way that dilutes or otherwise infringes upon the
trademark rights of Conservancy and the Git Project in the
Marks.</p></li>
<li><p>To refer to the Git software, modified by a third party to the point of
inoperability with Git software in substantially unmodified form.</p></li>
</ul>

<p>In addition, you may not use any of the Marks as a syllable in a new word
or as part of a portmanteau (e.g., "Gitalicious", "Gitpedia") used as a
mark for a third-party product or service without Conservancy's written
permission.  For the avoidance of doubt, this provision applies even to
third-party marks that use the Marks as a syllable or as part of a
portmanteau to refer to a product or service's use of Git code.</p>

<h3>2.4 Limitations to this Policy</h3>

<p>This Policy does not confer any rights to use the trademarks
"Software Freedom Conservancy," "Conservancy," or to use any other
trademarks other than the Marks listed in Section 1. This Policy
does not authorize you to act as an agent for Conservancy, enter
into any agreement on behalf of or otherwise create any
liability for the Git Project or Conservancy.</p>

<h3>2.5 Use of the Marks in merchandising</h3>

<p>You may not create and/or sell merchandise bearing any of the Marks
without Conservancy's express written permission.  If you are interested
in using creating and/or selling merchandise bearing any of the the Marks,
please send proofs of your designs to us at
<a href="mailto:trademark@sfconservancy.org">TRADEMARK@SFCONSERVANCY.ORG</a>.
</p>

<h3>3 Rights reserved by Conservancy</h3>

<p>Conservancy reserves the sole right to:</p>

<ul>
<li><p>Determine compliance with this Policy.</p></li>
<li><p>Modify this Policy in ways consistent with its mission of
protecting the public.</p></li>
<li><p>Grant exceptions to this Policy, of any kind and for any reason
whatsoever, other clauses notwithstanding.</p></li>
</ul>

<h2>4 Questions</h2>

<p>This Policy is designed to keep the Marks safe in order to
protect this software's reputation, earned by the contributions
of the Git Project to the free and open source software
community and to the public at large. If you see any use of the Marks
anywhere that you think violates this Policy or otherwise goes against the
spirit of the Git Project and Conservancy's mission, please bring
it to Conservancy's attention by contacting us at
<a href="mailto:trademark@sfconservancy.org">TRADEMARK@SFCONSERVANCY.ORG</a>.
</p>

<p>If you have questions about using the Marks, or if you think you
should be able to use the Marks for any purpose not allowed by
this Policy and would like permission for that use, please contact
Conservancy by emailing
<a href="mailto:trademark@sfconservancy.org">TRADEMARK@SFCONSERVANCY.ORG</a>
or by writing to Git Project c/o Software Freedom Conservancy, 137
Montague St.  Ste 380, Brooklyn, NY 11201-3548.</p>

</div>